services:
  database:
    image: postgres:18
    shm_size: 512mb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgres_final:/var/lib/postgresql/data

    ports:
      - "5432:5432"